/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Header = {
  _type: "header";
  skipLinkText: InternationalizedArrayString;
  navLabel: InternationalizedArrayString;
  cta: Button;
};

export type Seo = {
  _type: "seo";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayBlockContent;
  ogImage?: InternationalizedArrayOgImage;
};

export type ServiceView = {
  _type: "serviceView";
  heroHeadline?: InternationalizedArrayString;
  heroDescription?: InternationalizedArrayString;
  packages?: Array<
    {
      _key: string;
    } & ServicePackage
  >;
  addOns?: Array<
    {
      _key: string;
    } & ServiceAddOn
  >;
  maintenancePlans?: Array<
    {
      _key: string;
    } & MaintenancePlan
  >;
  process?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
};

export type ProcessStep = {
  _type: "processStep";
  title: InternationalizedArrayString;
  description?: InternationalizedArrayBlockContent;
};

export type MaintenancePlan = {
  _type: "maintenancePlan";
  name: InternationalizedArrayString;
  price?: string;
  description?: InternationalizedArrayBlockContent;
  features?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  notIncluded?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
};

export type ServiceAddOn = {
  _type: "serviceAddOn";
  name: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  price?: string;
};

export type ServicePackage = {
  _type: "servicePackage";
  name: InternationalizedArrayString;
  price: string;
  description: InternationalizedArrayBlockContent;
  bestFor?: InternationalizedArrayString;
  deliverables?: Array<
    {
      _key: string;
    } & InternationalizedArrayString
  >;
  timeline?: InternationalizedArrayString;
  isPopular?: boolean;
};

export type OgImage = {
  _type: "ogImage";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  metadataBase?: string;
};

export type Link = {
  _type: "link";
  linkType?: "href" | "internal";
  href?: string;
  openInNewTab?: boolean;
  internal?:
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "home";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "resume";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "servicesPage";
      };
};

export type SocialLink = {
  _type: "socialLink";
  name?: string;
  url: string;
};

export type Button = {
  _type: "button";
  text: InternationalizedArrayString;
  link: Link;
};

export type Duration = {
  _type: "duration";
  start?: string;
  end?: string;
};

export type Milestone = {
  _type: "milestone";
  title: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  duration: Duration;
};

export type Timeline = {
  _type: "timeline";
  items?: Array<{
    title?: string;
    milestones?: Array<
      {
        _key: string;
      } & Milestone
    >;
    _type: "item";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "href" | "post";
    href?: string;
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  message: string;
  createdAt?: string;
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: InternationalizedArrayBlockContent;
  dateIssued?: string;
  link?: string;
};

export type InternationalizedArrayBlockContent = Array<
  {
    _key: string;
  } & InternationalizedArrayBlockContentValue
>;

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: string;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  position?: string;
  isCurrent?: boolean;
  startDate: string;
  endDate?: string;
  description: InternationalizedArrayBlockContent;
  todayText?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  type: "technical" | "soft";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: InternationalizedArrayString;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: InternationalizedArrayBlockContent;
  duration?: string;
  sourceLink?: string;
  websiteLink?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  slug: Slug;
  selectionTitle?: InternationalizedArrayString;
  selectionDescription?: InternationalizedArrayString;
  technicalOptionLabel?: InternationalizedArrayString;
  technicalOptionDescription?: InternationalizedArrayString;
  solutionOptionLabel?: InternationalizedArrayString;
  solutionOptionDescription?: InternationalizedArrayString;
  technicalView?: ServiceView;
  solutionView?: ServiceView;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Resume = {
  _id: string;
  _type: "resume";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  slug: Slug;
  title: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  showSkills?: boolean;
  showProjects?: boolean;
  showCertificates?: boolean;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title: InternationalizedArrayString;
  headline: InternationalizedArrayString;
  tagline: InternationalizedArrayBlockContent;
  renovationLabelPrimary: InternationalizedArrayString;
  renovationLabelSecondary: InternationalizedArrayString;
  findMeOnLabel: InternationalizedArrayString;
  resumeButtonLabel: InternationalizedArrayString;
  profile: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "profile";
  };
  ctaButtons?: Array<
    {
      _key: string;
    } & Button
  >;
  featuredProjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  footer: InternationalizedArrayString;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  motto?: InternationalizedArrayString;
  about?: InternationalizedArrayString;
  location?: InternationalizedArrayString;
  picture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  workPreference?: InternationalizedArrayString;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  title: InternationalizedArrayString;
  description: InternationalizedArrayBlockContent;
  header: Header;
};

export type InternationalizedArrayOgImage = Array<
  {
    _key: string;
  } & InternationalizedArrayOgImageValue
>;

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type InternationalizedArrayImageValue = {
  _type: "internationalizedArrayImageValue";
  value?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type InternationalizedArrayOgImageValue = {
  _type: "internationalizedArrayOgImageValue";
  value?: OgImage;
};

export type InternationalizedArrayBlockContentValue = {
  _type: "internationalizedArrayBlockContentValue";
  value?: BlockContent;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type InternationalizedArrayImage = Array<
  {
    _key: string;
  } & InternationalizedArrayImageValue
>;

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  slug: Slug;
  content?: InternationalizedArrayBlockContent;
  excerpt?: InternationalizedArrayString;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Header
  | Seo
  | ServiceView
  | ProcessStep
  | MaintenancePlan
  | ServiceAddOn
  | ServicePackage
  | OgImage
  | Link
  | SocialLink
  | Button
  | Duration
  | Milestone
  | Timeline
  | SanityImageCrop
  | SanityImageHotspot
  | BlockContent
  | Contact
  | Certificate
  | InternationalizedArrayBlockContent
  | Job
  | Skill
  | Project
  | InternationalizedArrayString
  | ServicesPage
  | Slug
  | Resume
  | Home
  | Profile
  | Settings
  | InternationalizedArrayOgImage
  | MediaTag
  | InternationalizedArrayImageValue
  | InternationalizedArrayOgImageValue
  | InternationalizedArrayBlockContentValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayImage
  | Post
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{    ...,    header{      ...,      cta{          ...,  link{      ...,  href,  internal->{    _type,    "slug": slug.current  }  }      }    }  }
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  title: InternationalizedArrayString;
  description: InternationalizedArrayBlockContent;
  header: {
    _type: "header";
    skipLinkText: InternationalizedArrayString;
    navLabel: InternationalizedArrayString;
    cta: {
      _type: "button";
      text: InternationalizedArrayString;
      link: {
        _type: "link";
        linkType?: "href" | "internal";
        href: string | null;
        openInNewTab?: boolean;
        internal:
          | {
              _type: "home";
              slug: null;
            }
          | {
              _type: "resume";
              slug: string;
            }
          | {
              _type: "servicesPage";
              slug: string;
            }
          | null;
      };
    };
  };
} | null;
// Variable: homeQuery
// Query: *[_type == "home"][0]{    ...,    ctaButtons[]{        ...,  link{      ...,  href,  internal->{    _type,    "slug": slug.current  }  }    },    profile->{      name,      email,      phone,      motto,      about,      location,      picture,      workPreference,      socialLinks[]{        name,        url      }    },    featuredProjects[]->{      _id,      name,      description,      "image": coverImage,      "technologies": skills[]->name,      "link": websiteLink,      "github": sourceLink,      featured    },    footer  }
export type HomeQueryResult = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title: InternationalizedArrayString;
  headline: InternationalizedArrayString;
  tagline: InternationalizedArrayBlockContent;
  renovationLabelPrimary: InternationalizedArrayString;
  renovationLabelSecondary: InternationalizedArrayString;
  findMeOnLabel: InternationalizedArrayString;
  resumeButtonLabel: InternationalizedArrayString;
  profile: {
    name: string | null;
    email: string | null;
    phone: string | null;
    motto: InternationalizedArrayString | null;
    about: InternationalizedArrayString | null;
    location: InternationalizedArrayString | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    workPreference: InternationalizedArrayString | null;
    socialLinks: Array<{
      name: string | null;
      url: string;
    }> | null;
  };
  ctaButtons: Array<{
    _key: string;
    _type: "button";
    text: InternationalizedArrayString;
    link: {
      _type: "link";
      linkType?: "href" | "internal";
      href: string | null;
      openInNewTab?: boolean;
      internal:
        | {
            _type: "home";
            slug: null;
          }
        | {
            _type: "resume";
            slug: string;
          }
        | {
            _type: "servicesPage";
            slug: string;
          }
        | null;
    };
  }> | null;
  featuredProjects: Array<{
    _id: string;
    name: InternationalizedArrayString;
    description: InternationalizedArrayBlockContent | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    technologies: Array<string> | null;
    link: string | null;
    github: string | null;
    featured: null;
  }> | null;
  footer: InternationalizedArrayString;
} | null;
// Variable: homeFooterQuery
// Query: *[_type == "home"][0]{    footer,    profile->{      name    }  }
export type HomeFooterQueryResult = {
  footer: InternationalizedArrayString;
  profile: {
    name: string | null;
  };
} | null;
// Variable: profileQuery
// Query: *[_type == "profile"][0]{    _id,    name,    email,    phone,    motto,    about,    location,    picture,    workPreference,    socialLinks[]{      platform,      url    }  }
export type ProfileQueryResult = {
  _id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  motto: InternationalizedArrayString | null;
  about: InternationalizedArrayString | null;
  location: InternationalizedArrayString | null;
  picture: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  workPreference: InternationalizedArrayString | null;
  socialLinks: Array<{
    platform: null;
    url: string;
  }> | null;
} | null;
// Variable: resumeQuery
// Query: *[_type == "resume"][0]{    _id,    title,    description,    showSkills,    showProjects,    showCertificates  }
export type ResumeQueryResult = {
  _id: string;
  title: InternationalizedArrayString;
  description: InternationalizedArrayString | null;
  showSkills: boolean | null;
  showProjects: boolean | null;
  showCertificates: boolean | null;
} | null;
// Variable: servicesPageQuery
// Query: *[_type == "servicesPage"][0]
export type ServicesPageQueryResult = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  slug: Slug;
  selectionTitle?: InternationalizedArrayString;
  selectionDescription?: InternationalizedArrayString;
  technicalOptionLabel?: InternationalizedArrayString;
  technicalOptionDescription?: InternationalizedArrayString;
  solutionOptionLabel?: InternationalizedArrayString;
  solutionOptionDescription?: InternationalizedArrayString;
  technicalView?: ServiceView;
  solutionView?: ServiceView;
} | null;
// Variable: allJobsQuery
// Query: *[_type == "job"] | order(startDate desc){    _id,    position,    company,    location,    startDate,    endDate,    "current": isCurrent,    description,    responsibilities,    "technologies": skills[]->name  }
export type AllJobsQueryResult = Array<{
  _id: string;
  position: string | null;
  company: string;
  location: null;
  startDate: string;
  endDate: string | null;
  current: boolean | null;
  description: InternationalizedArrayBlockContent;
  responsibilities: null;
  technologies: Array<string> | null;
}>;
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(_createdAt desc){    _id,    name,    description,    "image": coverImage,    "technologies": skills[]->name,    "link": websiteLink,    "github": sourceLink,    featured,    duration  }
export type AllProjectsQueryResult = Array<{
  _id: string;
  name: InternationalizedArrayString;
  description: InternationalizedArrayBlockContent | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  technologies: Array<string> | null;
  link: string | null;
  github: string | null;
  featured: null;
  duration: string | null;
}>;
// Variable: allSkillsQuery
// Query: *[_type == "skill"] | order(name asc){    _id,    name,    type  }
export type AllSkillsQueryResult = Array<{
  _id: string;
  name: string;
  type: "soft" | "technical";
}>;
// Variable: allCertificatesQuery
// Query: *[_type == "certificate"] | order(dateIssued desc)
export type AllCertificatesQueryResult = Array<{
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: InternationalizedArrayBlockContent;
  dateIssued?: string;
  link?: string;
}>;
// Variable: sitemapData
// Query: *[_type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<{
  slug: string;
  _type: "post";
  _updatedAt: string;
}>;
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  }
export type AllPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: InternationalizedArrayString;
  slug: string;
  excerpt: InternationalizedArrayString | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date: string;
}>;
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  }
export type MorePostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: InternationalizedArrayString;
  slug: string;
  excerpt: InternationalizedArrayString | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date: string;
}>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  }
export type PostQueryResult = {
  content: InternationalizedArrayBlockContent | null;
  _id: string;
  status: "draft" | "published";
  title: InternationalizedArrayString;
  slug: string;
  excerpt: InternationalizedArrayString | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date: string;
} | null;
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "settings"][0]{\n    ...,\n    header{\n      ...,\n      cta{\n        \n  ...,\n  link{\n    \n  ...,\n  href,\n  internal->{\n    _type,\n    "slug": slug.current\n  }\n\n  }\n\n      }\n    }\n  }\n': SettingsQueryResult;
    '\n  *[_type == "home"][0]{\n    ...,\n    ctaButtons[]{\n      \n  ...,\n  link{\n    \n  ...,\n  href,\n  internal->{\n    _type,\n    "slug": slug.current\n  }\n\n  }\n\n    },\n    profile->{\n      name,\n      email,\n      phone,\n      motto,\n      about,\n      location,\n      picture,\n      workPreference,\n      socialLinks[]{\n        name,\n        url\n      }\n    },\n    featuredProjects[]->{\n      _id,\n      name,\n      description,\n      "image": coverImage,\n      "technologies": skills[]->name,\n      "link": websiteLink,\n      "github": sourceLink,\n      featured\n    },\n    footer\n  }\n': HomeQueryResult;
    '\n  *[_type == "home"][0]{\n    footer,\n    profile->{\n      name\n    }\n  }\n': HomeFooterQueryResult;
    '\n  *[_type == "profile"][0]{\n    _id,\n    name,\n    email,\n    phone,\n    motto,\n    about,\n    location,\n    picture,\n    workPreference,\n    socialLinks[]{\n      platform,\n      url\n    }\n  }\n': ProfileQueryResult;
    '\n  *[_type == "resume"][0]{\n    _id,\n    title,\n    description,\n    showSkills,\n    showProjects,\n    showCertificates\n  }\n': ResumeQueryResult;
    '*[_type == "servicesPage"][0]': ServicesPageQueryResult;
    '\n  *[_type == "job"] | order(startDate desc){\n    _id,\n    position,\n    company,\n    location,\n    startDate,\n    endDate,\n    "current": isCurrent,\n    description,\n    responsibilities,\n    "technologies": skills[]->name\n  }\n': AllJobsQueryResult;
    '\n  *[_type == "project"] | order(_createdAt desc){\n    _id,\n    name,\n    description,\n    "image": coverImage,\n    "technologies": skills[]->name,\n    "link": websiteLink,\n    "github": sourceLink,\n    featured,\n    duration\n  }\n': AllProjectsQueryResult;
    '\n  *[_type == "skill"] | order(name asc){\n    _id,\n    name,\n    type\n  }\n': AllSkillsQueryResult;
    '\n  *[_type == "certificate"] | order(dateIssued desc)\n': AllCertificatesQueryResult;
    '\n  *[_type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult;
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n\n  }\n': AllPostsQueryResult;
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n\n  }\n': MorePostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content,\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n\n  }\n': PostQueryResult;
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult;
  }
}
